# cloudbuild.yaml
steps:
# Build the Docker image using the Dockerfile in the same directory
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  # Tag the image with the specific commit SHA for traceability
  # Substitutions _AR_REGION, _AR_REPO_NAME, _SERVICE_NAME are defined in the trigger
  - '${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '.' # Build context is the current directory (repo root)

# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

# Deploy the new image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}' # Service name (e.g., phronesis-nexus)
  - '--image'
  - '${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}' # Use the image tagged with SHA
  - '--platform'
  - 'managed' # Use the fully managed Cloud Run
  - '--region'
  - '${_AR_REGION}' # Region for Cloud Run deployment
  - '--allow-unauthenticated' # Keep this if you want the app publicly accessible
  # Remove '--allow-unauthenticated' and add '--no-allow-unauthenticated' if you need authentication
  # --project is automatically set by Cloud Build

timeout: '1600s' # Increase timeout if build/deploy takes longer than 10 mins

# This option must be at the top level, aligned with 'steps' and 'timeout'
options:
  logging: CLOUD_LOGGING_ONLY
